SOURCES = modules.f90 ab.f90 arhbt.f90 arhim.f bifg21.f90 \
          bifgel.f90 bifoag.f90 cyklap.f90 eigQR.f90 farhim.f90 \
          funht.f90 funns.f90 galgel.f90 grsyst.f90 htxyl.f90 \
          htxynl.f90 newtap.f90 newtlap.f90 nsxyar.f90 nsxyl.f90 \
          nsxynl.f90 pollin.f90 polnel.f90 pro.f90 syshtL.f90 \
          syshtN.f90 sysnsL.f90 sysnsN.f90 tempbt.f90 tempo.f90 \
          tminit.f90 tnelgo.f90 tsubo.f90 vxrigid.f90 vyfree.f90 \
          xconduc.f90 yadiab.f90 lapak.f90

OUTPUT = galgel
COMMAND = galgel < galgel.in

USE_FORTRAN = 1

-include ../Makefile.config

