SOURCES = dcabs1.f dlaran.f dlarnd.f dznrm2.f gammul.f init.f lsame.f matmul.f muldeo.f muldoe.f phinit.f rndcnf.f rndphi.f su3mul.f uinith.f wupwise.f xerbla.f zaxpy.f zcopy.f zdotc.f zgemm.f zscal.f
OUTPUT = wupwise

COMMAND = wupwise < wupwise.in

USE_FORTRAN = 1

-include ../Makefile.config

