SOURCES = scanner.c

OUTPUT = art
COMMAND = art -scanfile c756hel.in -trainfile1 a10.img -trainfile2 hc.img -stride 2 -startx 110 -starty 200 -endx 160 -endy 240 -objects 10 > ref.out

-include ../Makefile.config
