SOURCES = analyze-linkage.c and.c build-disjuncts.c extract-links.c \
          fast-match.c idiom.c main.c massage.c parse.c \
          post-process.c print.c prune.c read-dict.c utilities.c \
          xalloc.c word-file.c strncasecmp.c

OUTPUT = parser

COMMAND = parser 2.1.dict -batch < ref.in

-include ../Makefile.config
