SOURCES = ammp.c eval.c analyze.c anonbon.c noel.c animate.c atoms.c bonds.c \
          angle.c gsdg.c hybrid.c unonbon.c rectmm.c vnonbon.c tgroup.c \
	        tset.c tailor.c torsion.c optimist.c variable.c math.c mom.c \
	        monitor.c significance.c random.c tether.c restrain.c box.c

OUTPUT = ammp
COMMAND = ammp < ammp.in > ammp.out

-include ../Makefile.config
