SOURCES = FaceRecTypes.f90 \
          parameterRoutines.f90 \
          cfftb.f90 cfftf.f90 cffti.f90 fft2d.f90 \
          gaborRoutines.f90 imageRoutines.f90 graphRoutines.f90 \
          FaceRec.f90

OUTPUT = facerec
COMMAND = facerec < ref.in

USE_FORTRAN = 1

-include ../Makefile.config

