SOURCES = fma3d.f90 beam_.f90 include_file_.f90 penta_.f90 segment_set_.f90 \
          body_force_.f90 indx_.f90 periodic_bc_.f90 \
          sliding_interface_.f90 constrained_node_.f90 layering_.f90 \
          plate_pair_.f90 sliding_node_.f90 contact_node_.f90 \
          location_.f90 platq_.f90 spot_weld_.f90 contact_surface_.f90 \
          lsold_.f90 platt_.f90 spring_.f90 coord_.f90 massprop_.f90 \
          pressure_bc_.f90 spring_bc_.f90 damper_.f90 material_.f90 \
          property_.f90 state_variables_.f90 damper_bc_.f90 \
          mean_stress_.f90 shared_common_data.f90 stress_.f90 \
          displacement_bc_.f90 membq_.f90 qa_record_.f90 \
          tabulated_function_.f90 element_set_.f90 membt_.f90 \
          relink_scratch_.f90 tetra_.f90 enumerated_sets_.f90 motion_.f90 \
          results_.f90 tied_bc_.f90 force_.f90 nodal_point_mass_.f90 \
          rigid_body_.f90 truss_.f90 force_bc_.f90 node_.f90 \
          rigid_body_mass_.f90 value_.f90 gauge1d_.f90 node_set_.f90 \
          rigid_wall_bc_.f90 velocity_ic_.f90 gauge2d_.f90 \
          nonreflecting_bc_.f90 section_1d_.f90 gauge3d_.f90 \
          nrbc_data_.f90 section_2d_.f90 hexah_.f90 output_.f90 segment_.f90 \
          lsold.f90 damper.f90 spring.f90 material_00.f90 material_10.f90 \
          material_11.f90 material_17.f90 material_22.f90 material_25.f90 \
          material_32.f90 material_33.f90 material_34a.f90 material_36.f90 \
          material_38.f90 material_dm.f90 material_sp.f90 sort.f90 \
          pdb.f90 beam.f90 membq.f90 membt.f90 penta.f90 tetra.f90 hexah.f90 \
          platq.f90 truss.f90 platt.f90 fma1.f90 getirv.f90 relink.f90 \
          output.f90 fma2.f90 partition.f90 strain.f90 slide.f90

OUTPUT = fma3d
COMMAND = fma3d

USE_FORTRAN = 1

-include ../Makefile.config

