# Input set for SPEC CPU2000 253.perlbmk
%headers = (
  'X-Openmail-Hops' => [
    'X-Openmail-Hops: 1'
  ],
  'Priority' => [
    'Priority: normal',
    'Priority: Normal'
  ],
  'X-Incognito-Version' => [
    'X-Incognito-Version: 4.10.1'
  ],
  'To' => [
    'To: foofie@baz.monkey.com',
    'To: barney@autoparts.autoparts.bar.whale.com',
    'To: barney@bar.Godzilla.monkey.com',
    'To: barrel@gibbon.teletubbies.xyzzy.com',
    'To: foofie@whale.foo.com',
    'To: mopsy@xyzzy.wubble.fish.gibbon.com',
    'To: yoshi@wubble.xyzzy.bar.com',
    'To: fred@xyzzy.baz.foo.com',
    'To: cloud@xyzzy.fish.whale.foo.com',
    'To: cloud@fish.fish.teletubbies.com',
    'To: george@wubble.wubble.fish.com',
    'To: foofie@foo.Godzilla.bar.com',
    'To: flopsy@foo.gibbon.monkey.Godzilla.com',
    'To: wilma@xyzzy.foo.baz.foo.com',
    'To: barrel@whale.com',
    'To: foofie@autoparts.autoparts.gibbon.com',
    'To: ralph@bar.com',
  ],
  'X-Yow' => [
    'X-Yow: If this was a SWEDISH MOVIE, I\'d take off your GO-GO BOOTS!!',
    'X-Yow: A can of ASPARAGUS, 73 pigeons, some LIVE ammo, and a FROZEN DAQUIRI!!',
    'X-Yow: A dwarf is passing out somewhere in Detroit!',
    'X-Yow: A GRAM??  A BRAM...  A GROOM...  A BROOM...  Oh, Yeh!!  Wash the  ROOM!!',
    'X-Yow: ...A housewife is wearing a polypyrene jumpsuit!!',
    'X-Yow: A wide-eyed, innocent UNICORN, poised delicately in a MEADOW filled with  LILACS, LOLLIPOPS & small CHILDREN at the HUSH of twilight??',
    'X-Yow: Actually, what I\'d like is a little toy spaceship!!',
    'X-Yow: After this, I\'m going to BURN some RUBBER!!',
    'X-Yow: After THIS, let\'s go to PHILADELPHIA and have TRIPLETS!!',
    'X-Yow: AIEEEEE!  I am having an UNDULATING EXPERIENCE!',
    'X-Yow: ALFRED JARRY!  Say something about th\' DEATH of DISCO!!',
    'X-Yow: All I can think of is a platter of organic PRUNE CRISPS being trampled  by an army of swarthy, Italian LOUNGE SINGERS...',
    'X-Yow: All of a sudden, I want to THROW OVER my promising ACTING CAREER,  grow a LONG BLACK BEARD and wear a BASEBALL HAT!!  ...  Although I don\'t know WHY!!',
    'X-Yow: All of life is a blur of Republicans and meat!',
    'X-Yow: All right, you degenerates!  I want this place evacuated in 20 seconds!',
    'X-Yow: All this time I\'ve been VIEWING a RUSSIAN MIDGET SODOMIZE a HOUSECAT!',
    'X-Yow: Alright, you!!  Imitate a WOUNDED SEAL pleading for a PARKING SPACE!!',
    'X-Yow: Am I accompanied by a PARENT or GUARDIAN?',
    'X-Yow: Am I elected yet?',
    'X-Yow: ..Am I in a SOAP OPERA??',
    'X-Yow: Am I in GRADUATE SCHOOL yet?',
  ],
  '>Received' => [
    '>Received: from Godzilla.teletubbies.xyzzy.org by gibbon.teletubbies.whale.com (4.1/SMI-4.1/Email 2.1 10/25/93) id AA03929 for yoshi@quux.com; Fri, 13 Jun 97 10:42:47 MST',
    '>Received: from wubble.baz.org by bar.com (4.1/SMI-4.1/Email 2.1 10/25/93) id AA03929 for cloud@autoparts.com; Fri, 13 Jun 97 10:42:47 MST'
  ],
  'Read-Receipt-To' => [
    'Read-Receipt-To: "Bruce Wang" <foofie@Godzilla.com>'
  ],
  'Cc' => [
    'Cc: yoshi@fish.whale.com',
    'Cc: barrel@fish.foo.gibbon.Godzilla.com',
    'Cc: mopsy@wubble.com',
    'Cc: ralph@gibbon.bar.foo.com',
    'Cc: boopsie@fish.Godzilla.com',
    'Cc: el_cider@baz.whale.baz.quux.com',
    'Cc: george@whale.fish.com',
    'Cc: barney@fish.fish.com',
    'Cc: wilma@fish.com',
    'Cc: yoshi@fish.xyzzy.Godzilla.com',
    'Cc: ralph@monkey.com',
    'Cc: cloud@wubble.foo.wubble.foo.com',
    'Cc: wilma@quux.com',
    'Cc: mopsy@foo.foo.com',
  ],
  'Received' => [
    'Received: by teletubbies.com (111.26.41.61/15.5+IOS 3.22) id AA03289; Fri, 3 Apr 1998 08:02:55 -0700',
    'Received: from orsmsx27.INTEL.COM (fish.quux.com [267.666.147.571]) by whale.com (8.8.6/8.8.5) with ESMTP id KAA10221 for <barney@monkey.teletubbies.org>; Wed, 10 Jun 1998 10:13:08 -0700 (PDT)',
    'Received: (from flopsy@localhost) by whale.Godzilla.Godzilla.org (8.8.8/8.8.8) id PAA06299 for gpcmail-out; Thu, 14 May 1998 15:07:41 -0400',
    'Received: (from el_cider@localhost) by Godzilla.teletubbies.org (8.8.8/8.8.8) id TAA30301 for gpcopc-out; Fri, 15 May 1998 19:26:41 -0400',
    'Received: from baz.net by xyzzy.org with ESMTP (498.181.312.178/16.2) id AA074447363; Fri, 10 Oct 1997 05:42:43 -0700',
    'Received: from eeWxN6ify (unverified [719.99.470.174]) by papayus.topnet.fr (EMWAC SMTPRS 0.83) with SMTP id <barney@papayus.topnet.fr>; Sun, 08 Mar 1998 21:02:45 +0100',
    'Received: from foo.quux.monkey.foo.com ([512.615.217.28]) by foo.teletubbies.org with ESMTP (627.583.752.261/16.2) id AA267569403; Sat, 21 Feb 1998 08:43:23 -0800',
    'Received: from autoparts.baz.com (fish.com [302.175.727.709]) by gibbon.teletubbies.com (8.8.8/8.8.8/WV1.0b) with SMTP id MAA04024 for <barrel@fish.baz.org>; Wed, 7 Jan 1998 12:04:37 -0800 (PST)',
    'Received: from teletubbies.Godzilla.com by bar.org with ESMTP (304.548.508.384/16.2) id AA186299253; Mon, 15 Sep 1997 11:47:33 -0700',
    'Received: from who ([212.111.497.318]) by whipboy.VSISInc.COM (8.8.4/8.8.4) with SMTP id JAA06710; Tue, 1 Jul 1997 09:05:54 -0700 (PDT)',
    'Received: from Godzilla.gibbon.com by quux.monkey.com (5.65/rmc-22feb94) id AA10383; Tue, 24 Jun 97 12:46:57 -0400',
    'Received: from gibbon.fish.monkey.com (autoparts.baz.com [134.749.1.283]) by quux.teletubbies.quux.Godzilla.com (8.8.5/DELL-INET-10-14-1997) with SMTP id QAA21002; Mon, 11 May 1998 16:24:39 -0600 (GMT)',
    'Received: from teletubbies.net(really [164/187]) by monkey.Godzilla.autoparts.gibbon.com Friday, June 19th, 1998',
    'Received: from quux.com (autoparts.fish.fish.xyzzy.com [319.396.290.339]) by wubble.wubble.xyzzy.com with SMTP (8.7.1/8.7.1) id PAA18638 for <el_cider@foo.org>; Thu, 25 Jun 1998 15:11:43 -0600 (MDT)',
    'Received: (from barney@localhost) by foo.org (8.8.8/8.8.8) id RAA18547 for apcsolid-out; Tue, 2 Jun 1998 17:02:52 -0400',
    'Received: from Godzilla.gibbon.xyzzy.com by autoparts.org with SMTP (658.213.624.511/16.2) id AA230904902; Wed, 17 Sep 1997 15:21:42 -0700',
    'Received: from Godzilla.autoparts.whale.com (Godzilla.fish.com [145.170.364.290]) by autoparts.xyzzy.org (8.9.0/8.9.0) with SMTP id MAA04807 for <fred@foo.wubble.monkey.org>; Tue, 16 Jun 1998 12:26:03 -0400',
    'Received: from quux.wubble.xyzzy.de (teletubbies.fish.Godzilla.autoparts.de [547.598.597.77]) by xyzzy.baz.de (8.8.6/8.8.6) with SMTP id QAA19909; Thu, 24 Jul 1997 16:23:55 +0200 (MDT)',
    'Received: from xyzzy.baz.gibbon.whale.org (monkey.autoparts.xyzzy.org [68.25.612.733]) by quux.whale.org (8.8.8/8.8.8) with SMTP id KAA10986; Wed, 25 Mar 1998 10:41:39 -0500',
    'Received: by baz.teletubbies.teletubbies.com (417.763.368.63/16.2) id AA066065413; Thu, 9 Apr 1998 11:10:13 -0700',
    'Received: from whale.com by fish.bar.foo.xyzzy.com (SMI-8.6/SMI-SVR4) id NAA26561; Mon, 1 Jun 1998 13:17:48 -0400',
    'Received: from fish.autoparts.com ([192.348.320.214]) by Mclean.Sparta.Com (8.8.5/8.8.5) with SMTP id PAA00668 for <ralph@xyzzy.foo.monkey.org>; Fri, 31 Jul 1998 15:47:03 -0400 (EDT)',
    'Received: from Bob (whale.fish.net [22.746.462.70]) by monkey.baz.Godzilla.wubble.net (8.8.8/v1.0) with SMTP id LAA29607; Mon, 3 Aug 1998 11:15:10 -0400 (EDT)',
    'Received: from xyzzy.quux.bar.com by monkey.whale.org with ESMTP (139.397.503.185/16.2) id AA159026959; Thu, 16 Oct 1997 08:49:19 -0700',
  ],
  'X-Priority' => [
    'X-Priority: 1',
    'X-Priority: 2 (High)',
    'X-Priority: 3',
    'X-Priority: 3 (Normal)',
    'X-Priority: 1 (Highest)'
  ],
  'X400-Trace' => [
    'X400-Trace: us*attmail*dell computer; Arrival 12 Nov 97 18:09 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 11 May 98 17:24 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 12 May 98 11:38 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 22 May 98 14:25 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 14 Jul 97 15:52 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 30 Sep 97 18:54 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 17 Sep 97 16:07 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 19 May 98 11:28 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 29 Jan 98 18:21 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 4 Sep 97 20:12 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 24 Sep 97 09:48 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 3 Jun 98 15:01 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 2 Mar 98 15:53 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 26 Feb 98 16:42 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 19 Nov 97 15:10 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 26 Nov 97 11:27 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 29 Apr 98 10:50 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 30 Jul 97 18:11 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 27 Apr 98 13:27 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 15 May 98 17:51 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 17 Jul 97 09:10 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 14 Mar 98 20:16 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 25 Jul 97 13:54 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 17 Mar 98 09:10 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 22 Jul 97 16:58 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 16 Jul 97 15:47 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 16 Mar 98 16:15 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 10 Nov 97 16:21 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 20 Nov 97 12:06 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 10 Oct 97 12:13 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 7 May 98 15:37 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 3 Mar 98 14:45 CST Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 7 May 98 17:56 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 26 Sep 97 11:00 CDT Action: Relayed',
    'X400-Trace: us*attmail*dell computer; Arrival 10 Jan 98 12:52 CST Action: Relayed'
  ],
  'X-Ms-Tnef-Correlator' => [
    'X-Ms-Tnef-Correlator: 0000000085B329B6ACE3CF11821E444553540000A44F4A00'
  ],
  'Content-Description' => [
    'Content-Description: cc:Mail note part'
  ],
  'X-Received' => [
    'X-Received: from localhost by gibbon.Godzilla.edu (SMI-8.6/SMI-SVR4) id RAA24475; Thu, 18 Sep 1997 17:20:09 -0400'
  ],
  'X-MimeOLE' => [
    'X-MimeOLE: Produced By Microsoft MimeOLE V4.72.2106.4',
    'X-MimeOLE: Produced By Microsoft MimeOLE V4.72.3110.3',
    'X-MimeOLE: Produced By Microsoft MimeOLE V4.72.3007.0'
  ],
  'Content-MD5' => [
    'Content-MD5: vpUE/YdMMKkeB8iCmPdldg==',
    'Content-MD5: ZPz10Z+jS8C8LkOre9Pi1g==',
    'Content-MD5: igs16oT7mIen9SHY+aJyXA==',
    'Content-MD5: NnVy/xl2bF+/eSXc7znr/A==',
    'Content-MD5: 6DRN31/qPtMdrJNhtuubDA==',
    'Content-MD5: D6U3t4wqpFpxR0/Q1BPuQQ==',
    'Content-MD5: f6tjmEJoIMkI9pIgF+Y5ow==',
    'Content-MD5: uWv0yWohhcRcYFbxAxY3wA==',
    'Content-MD5: lbz9yV8UEIb9sTNl9np1Jw==',
    'Content-MD5: XmASTf0/3VuwUqNnhs9EYw==',
    'Content-MD5: h5NojAiJte7NjQwHLPAOvA==',
    'Content-MD5: Ywz4fg2Uoi6lFtCzKv7VCA==',
    'Content-MD5: RhtNWWDTVNYQGgsgwYk9Bg==',
    'Content-MD5: wdV/PtahpX3JeMFyfTmlhw==',
    'Content-MD5: 7TsFLu1U7dnitneI3WYBtQ==',
    'Content-MD5: HW7hOeqWieZcZeYyVShfSw==',
    'Content-MD5: mYq5MqN9wS3GJkWHTeoqPg==',
    'Content-MD5: yQqUnNWiEzHbPqGZap8KNA==',
    'Content-MD5: LUQVWdGADtv+lJ7FsoXcXQ==',
    'Content-MD5: /Y16ZmsUk3ycM2C0h+gN4w=='
  ],
  'Subject' => [
    'Subject: (gpcopc-418) DIGITAL\'s March 98 OPC submission',
    'Subject: (gpcopc-549) RE: Viewperf on CD ',
    'Subject: (gpcopc-107) pricing issues',
    'Subject: (gpcapc-359) Meeting minutes',
    'Subject: (gpcopc-347) Re: Re: Next submission deadline',
    'Subject: (gpcopc-419) 3Dlabs March 98 OPC submission',
    'Subject: (gpcapc-328) Quake2 questions',
    'Subject: (gpcopc-408) 4 GLperf tests',
    'Subject: (gpcapc-120) APC conference call minutes - 09/04/1997',
    'Subject: (gpcmbc-148) Initial test proposal',
    'Subject: (gpcopc-353) HP submits Jan \'98 OPC data',
    'Subject: (gpcapc-32) RE: VOTE on GPC Membership',
    'Subject: (gpcapc-99) No Mtg Today',
    'Subject: (gpcopc-162) Dynamic Pictures accepts Intergraphs Viewperf Submission',
    'Subject: (gpcopc-152) RE: SNI resubmitted GLperf results',
    'Subject: (gpcapc-240) Mtg Today!',
    'Subject: (gpcmail-35) Re: Sense8 Benchmark overview',
    'Subject: (gpcapc-17) Press Event at SIGGRAPH',
    'Subject: (apcquake-2) Quake II benchmark',
    'Subject: (gpcapc-182) Re: (gpcopc-324) Greg Passmore\'s e-mail address',
    'Subject: (gpcopc-19) Approval/rejection of submissions',
    'Subject: (gpcopc-79) RE: GPC News',
    'Subject: (gpcmail-211) (specmail-137) Directions for July',
    'Subject: (gpcopc-192) RE: Re: ARB Request for Publishing Conformance Data',
    'Subject: (gpcmbc-39) GPC guidelines',
    'Subject: (gpcmbc-203) Availability of benchmark',
    'Subject: (gpcapc-93) Agenda Items',
    'Subject: (gpcopc-723) Re: which Viewperf version for upcoming sub',
    'Subject: (gpcmail-22) Nov meeting',
    'Subject: (gpcapc-389) Re: Solidworks Benchmark Vote',
    'Subject: (gpcopc-662) Re: Re: [Fwd: Re: How to submit viewperf results]',
  ],
  'From_' => [
    'From cloud@autoparts.quux.fish.org Wed May 20 09:01:10 1998',
    'From foofie@teletubbies.bar.org Wed May 6 23:36:18 1998',
    'From el_cider@monkey.autoparts.xyzzy.quux.org Thu Jun 4 12:16:51 1998',
    'From el_cider@bar.Godzilla.org Thu Apr 2 11:37:45 1998',
    'From yoshi@quux.org Mon Jun 29 20:10:35 1998',
    'From barney@foo.org Wed May 13 19:18:36 1998',
    'From boopsie@quux.autoparts.quux.whale.org Fri Jan 23 08:46:52 1998',
    'From barney@bar.Godzilla.foo.Godzilla.org Thu Jul 16 08:48:24 1998',
    'From fred@fish.bar.Godzilla.whale.org Sat Jan 10 10:59:47 1998',
    'From george@bar.whale.org Wed Feb 25 12:31:32 1998',
    'From el_cider@wubble.gibbon.wubble.org Fri Apr 17 14:53:59 1998',
    'From yoshi@monkey.wubble.foo.autoparts.org Fri Jul 10 23:21:53 1998',
    'From barrel@foo.autoparts.autoparts.foo.org Fri Jul 18 06:00:14 1997',
    'From flopsy@autoparts.baz.org Wed Jul 16 10:09:09 1997',
    'From cloud@fish.wubble.quux.foo.org Sun May 24 20:15:21 1998',
    'From barrel@wubble.com Wed Apr 1 11:56:00 1998',
    'From ralph@wubble.Godzilla.gibbon.org Sat Nov 15 09:34:34 1997',
    'From barrel@bar.fish.foo.org Thu Apr 2 11:38:46 1998',
    'From wilma@foo.xyzzy.teletubbies.org Tue Sep 9 09:19:31 1997',
    'From wilma@bar.monkey.org Fri Sep 19 08:06:06 1997',
    'From foofie@whale.teletubbies.fish.org Thu Feb 26 12:41:11 1998',
    'From barrel@xyzzy.org Tue Jul 8 15:31:16 1997',
    'From foofie@whale.baz.org Wed Jun 11 17:27:04 1997',
    'From fred@gibbon.fish.org Thu Dec 11 07:25:04 1997',
    'From cloud@gibbon.org Mon Jun 16 11:08:58 1997',
    'From foofie@gibbon.org Thu Jul 31 03:28:34 1997',
  ],
  'X-Ibm-Spook-Fodder' => [
    'X-Ibm-Spook-Fodder: This header is not IBM CONFIDENTIAL'
  ],
  'X-Mts' => [
    'X-Mts: smtp'
  ],
  'X-Organization' => [
    'X-Organization: Nylarathotep\'s alien unix diesel fertilizer spikes of doom'
  ],
  'X-Ms-Attachment' => [
    'X-Ms-Attachment: glpsubmt.doc 0 00-00-1980 00:00'
  ],
  'X-Schwa' => [
    'X-Schwa: The XENON(tm) coated header at left will flash red in the presence of any alien. Write to Schwa, Box 6064, Reno, NV 89513'
  ],
  'Resent-Date' => [
    'Resent-Date: Fri, 7 Aug 1998 15:30:26 -0500',
    'Resent-Date: Thu, 18 Sep 1997 17:22:31 -0400 (EDT)',
    'Resent-Date: Fri, 31 Jul 1998 13:11:42 -0500'
  ],
  'Reply-To' => [
    'Reply-To: barrel@foo.quux.com',
    'Reply-To: foofie@Godzilla.quux.teletubbies.net',
    'Reply-To: Ahmad Zandi <foofie@Eng.Sun.COM>',
    'Reply-To: Ahmad Zandi <george@Eng.Sun.COM>',
    'Reply-To: fred@monkey.teletubbies.teletubbies.bar.com',
    'Reply-To: yoshi@wubble.foo.xyzzy.fish.com',
    'Reply-To: flopsy@Godzilla.foo.com',
    'Reply-To: Travis Bryson <barrel@Eng.Sun.COM>',
    'Reply-To: ralph@fish.wubble.fish.com',
    'Reply-To: el_cider@nexo.es',
    'Reply-To: flopsy@Godzilla.wubble.org',
    'Reply-To: wilma@gibbon.com',
    'Reply-To: Ahmad Zandi <barrel@fish.quux.gibbon.com>',
    'Reply-To: foofie@whale.fish.wubble.com',
    'Reply-To: mopsy@monkey.monkey.org',
    'Reply-To: cloud@baz.monkey.com',
    'Reply-To: yoshi@monkey.teletubbies.autoparts.com',
    'Reply-To: barrel@bar.org',
    'Reply-To: foofie@teletubbies.net',
    'Reply-To: Ahmad Zandi <wilma@monkey.com>',
  ],
  'Resent-Message-Id' => [
    'Resent-Message-Id: <george@quux.com>',
    'Resent-Message-Id: <el_cider@csmaster>',
    'Resent-Message-Id: <barrel@bar.fish.whale.quux.com>'
  ],
  'X-Incognito-Sn' => [
    'X-Incognito-Sn: 368'
  ],
  'X-mailer' => [
    'X-mailer: Pegasus Mail for Win32 (v3.01a)',
    'X-mailer: Pegasus Mail for Win32 (v3.01b)'
  ],
  'Sender' => [
    'Sender: <el_cider@xyzzy.org>',
    'Sender: <cloud@xyzzy.Godzilla.gibbon.org>',
    'Sender: <ralph@whale.wubble.quux.org>',
    'Sender: barrel@bar.wubble.com',
    'Sender: <flopsy@bar.bar.bar.baz.com>',
    'Sender: <el_cider@bar.wubble.org>',
    'Sender: <wilma@fish.quux.fish.org>',
    'Sender: <boopsie@fish.autoparts.foo.org>',
    'Sender: <ralph@teletubbies.autoparts.org>',
    'Sender: <cloud@autoparts.teletubbies.org>',
    'Sender: <cloud@gibbon.fish.org>',
    'Sender: <boopsie@teletubbies.quux.com>',
    'Sender: <ralph@monkey.monkey.com>',
    'Sender: <fred@gibbon.autoparts.baz.com>',
    'Sender: <mopsy@quux.quux.foo.foo.com>',
    'Sender: <boopsie@Godzilla.org>',
    'Sender: <foofie@fish.Godzilla.whale.bar.org>',
    'Sender: <boopsie@autoparts.xyzzy.teletubbies.bar.org>',
    'Sender: <barrel@whale.monkey.org>',
    'Sender: <ralph@whale.teletubbies.org>',
    'Sender: <foofie@teletubbies.gibbon.org>',
    'Sender: <boopsie@whale.xyzzy.bar.gibbon.org>',
    'Sender: <wilma@foo.bar.wubble.org>',
    'Sender: <flopsy@Godzilla.gibbon.quux.org>',
    'Sender: <barrel@whale.baz.org>',
    'Sender: <yoshi@Godzilla.wubble.Godzilla.org>',
    'Sender: mopsy@quux.gibbon.wubble.com',
    'Sender: <flopsy@foo.fish.gibbon.gibbon.org>',
    'Sender: foofie@foo.whale.whale.com',
    'Sender: <boopsie@wubble.teletubbies.org>',
    'Sender: <boopsie@bar.foo.org>',
    'Sender: wilma@Godzilla.baz.monkey.com',
    'Sender: <ralph@teletubbies.baz.org>',
    'Sender: <mopsy@gibbon.baz.quux.teletubbies.org>',
  ],
  'Resent-To' => [
    'Resent-To: barrel@quux.baz.quux.org',
    'Resent-To: flopsy@monkey.xyzzy.bar.gibbon.org',
    'Resent-To: cloud@fish.xyzzy.monkey.org'
  ],
  'P1-Recipients' => [
    'P1-Recipients: cloud@xyzzy.gibbon.gibbon.foo.org,flopsy@bar.quux.foo.foo.org,el_cider@baz.Godzilla.monkey.bar.org,barney@wubble.autoparts.fish.gibbon.org,fred@foo.xyzzy.whale.quux.org,flopsy@foo.baz.autoparts.foo.org',
    'P1-Recipients: cloud@Godzilla.org',
    'P1-Recipients: george@Godzilla.com,yoshi@autoparts.com',
    'P1-Recipients: flopsy@monkey.bar.org,foofie@whale.gibbon.autoparts.org,cloud@autoparts.fish.monkey.org,barney@bar.gibbon.foo.org,el_cider@monkey.org,boopsie@foo.org',
    'P1-Recipients: fred@autoparts.baz.org',
    'P1-Recipients: yoshi@wubble.xyzzy.gibbon.teletubbies.com,fred@Godzilla.foo.teletubbies.org,fred@wubble.Godzilla.foo.org,foofie@quux.org,fred@monkey.org,mopsy@fish.gibbon.org,ralph@gibbon.org',
    'P1-Recipients: flopsy@fish.baz.quux.whale.org,cloud@fish.xyzzy.foo.org',
    'P1-Recipients: cloud@gibbon.baz.teletubbies.gibbon.com,ralph@bar.quux.quux.com',
    'P1-Recipients: fred@xyzzy.xyzzy.monkey.com,wilma@quux.teletubbies.org',
    'P1-Recipients: mopsy@baz.com,el_cider@autoparts.whale.whale.com',
    'P1-Recipients: foofie@bar.baz.monkey.Godzilla.org',
    'P1-Recipients: yoshi@autoparts.bar.baz.org',
    'P1-Recipients: cloud@quux.fish.gibbon.baz.com,fred@wubble.com',
    'P1-Recipients: mopsy@Godzilla.autoparts.foo.com,flopsy@wubble.monkey.com',
    'P1-Recipients: mopsy@quux.com,george@fish.quux.baz.fish.com',
    'P1-Recipients: el_cider@fish.com,yoshi@Godzilla.Godzilla.monkey.baz.com',
    'P1-Recipients: george@wubble.baz.autoparts.gibbon.com,boopsie@bar.xyzzy.xyzzy.com',
    'P1-Recipients: wilma@wubble.autoparts.org,george@bar.foo.com,ralph@gibbon.xyzzy.bar.teletubbies.org',
    'P1-Recipients: barney@teletubbies.quux.com,boopsie@xyzzy.org,fred@monkey.autoparts.Godzilla.com',
    'P1-Recipients: barrel@bar.org,boopsie@Godzilla.baz.foo.org,cloud@monkey.baz.org,flopsy@monkey.foo.monkey.Godzilla.org,wilma@foo.org,mopsy@fish.wubble.bar.org',
    'P1-Recipients: yoshi@teletubbies.quux.bar.monkey.org',
    'P1-Recipients: cloud@foo.quux.wubble.com,cloud@teletubbies.wubble.teletubbies.gibbon.org,george@Godzilla.bar.baz.Godzilla.org',
    'P1-Recipients: ralph@gibbon.foo.quux.org,wilma@whale.xyzzy.com,flopsy@wubble.org',
    'P1-Recipients: boopsie@autoparts.com,el_cider@quux.com',
    'P1-Recipients: wilma@teletubbies.bar.baz.fish.com,wilma@bar.fish.com',
    'P1-Recipients: foofie@monkey.com,boopsie@foo.com',
    'P1-Recipients: el_cider@xyzzy.foo.autoparts.com,fred@gibbon.monkey.gibbon.com,foofie@perfit.ZKO.DEC.Com',
    'P1-Recipients: fred@foo.com,boopsie@teletubbies.gibbon.autoparts.Godzilla.com',
    'P1-Recipients: cloud@gibbon.com,george@wubble.com',
    'P1-Recipients: foofie@bar.quux.whale.baz.com,george@wubble.quux.xyzzy.bar.com',
    'P1-Recipients: wilma@bar.Godzilla.com,mopsy@whale.bar.teletubbies.gibbon.com',
    'P1-Recipients: george@monkey.gibbon.com,ralph@whale.quux.baz.foo.com,wilma@bar.wubble.baz.foo.com',
    'P1-Recipients: fred@baz.Godzilla.autoparts.fish.org,barney@fish.org',
    'P1-Recipients: barney@gibbon.baz.foo.com,flopsy@autoparts.fish.wubble.wubble.com,barney@gibbon.fish.com',
    'P1-Recipients: barrel@wubble.org',
    'P1-Recipients: yoshi@Godzilla.baz.org,george@gibbon.monkey.org',
    'P1-Recipients: flopsy@whale.com,foofie@foo.com',
    'P1-Recipients: foofie@autoparts.org',
    'P1-Recipients: barrel@fish.fish.wubble.com,foofie@teletubbies.bar.whale.wubble.org,foofie@teletubbies.org,foofie@quux.xyzzy.baz.org,yoshi@foo.quux.baz.whale.org,barney@foo.bar.Godzilla.org,mopsy@teletubbies.teletubbies.org',
    'P1-Recipients: cloud@xyzzy.org,mopsy@fish.xyzzy.org,george@perfit.ZKO.DEC.Com',
    'P1-Recipients: barrel@quux.fish.xyzzy.com,ralph@gibbon.org,wilma@quux.org',
    'P1-Recipients: george@baz.autoparts.fish.org',
    'P1-Recipients: el_cider@gibbon.fish.org,foofie@quux.foo.org',
    'P1-Recipients: barrel@Godzilla.monkey.com,mopsy@bar.autoparts.autoparts.autoparts.com',
    'P1-Recipients: barney@fish.com,ralph@quux.whale.teletubbies.org,foofie@foo.whale.monkey.fish.com',
    'P1-Recipients: foofie@fish.monkey.org,boopsie@baz.whale.Godzilla.gibbon.org,wilma@gibbon.xyzzy.quux.foo.org,el_cider@bar.quux.wubble.xyzzy.org,george@xyzzy.foo.wubble.org,ralph@autoparts.org',
    'P1-Recipients: ralph@whale.fish.teletubbies.org',
    'P1-Recipients: foofie@baz.org,flopsy@xyzzy.foo.org,foofie@autoparts.org,yoshi@foo.org,george@xyzzy.Godzilla.org,cloud@xyzzy.whale.org',
    'P1-Recipients: george@quux.whale.autoparts.gibbon.org,ralph@whale.org,cloud@teletubbies.gibbon.org,ralph@fish.gibbon.monkey.org,el_cider@gibbon.foo.autoparts.gibbon.org,mopsy@xyzzy.baz.org',
    'P1-Recipients: foofie@baz.quux.foo.org',
    'P1-Recipients: cloud@whale.Godzilla.wubble.foo.org,barrel@baz.bar.bar.org',
    'P1-Recipients: ralph@wubble.foo.org',
    'P1-Recipients: george@quux.com,george@quux.quux.whale.org,el_cider@bar.org,barney@bar.monkey.bar.Godzilla.org,boopsie@monkey.org,barney@xyzzy.org,mopsy@fish.org'
  ],
  'cc' => [
    'cc: cloud@bar.teletubbies.fish.com'
  ],
  'X-Sender' => [
    'X-Sender: foofie@autoparts.gibbon.teletubbies.xyzzy.net',
    'X-Sender: boopsie@xyzzy.net',
    'X-Sender: boopsie@fish.autoparts.xyzzy.com',
    'X-Sender: foofie@autoparts.com',
    'X-Sender: wilma@teletubbies.quux.net',
    'X-Sender: wilma@Godzilla.Godzilla.net',
    'X-Sender: yoshi@fish.gibbon.net',
    'X-Sender: barney@fish.monkey.foo.com',
    'X-Sender: mopsy@xyzzy.bar.net',
    'X-Sender: ralph@quux.wubble.net',
    'X-Sender: barrel@teletubbies.bar.Godzilla.bar.net',
    'X-Sender: foofie@fish.com',
    'X-Sender: barrel@gibbon.monkey.quux.fish.com',
    'X-Sender: yoshi@teletubbies.gibbon.com',
    'X-Sender: cloud@Godzilla.bar.quux.xyzzy.net',
    'X-Sender: mopsy@xyzzy.foo.gibbon.com (Unverified)',
    'X-Sender: fred@wubble.net',
    'X-Sender: cloud@teletubbies.Godzilla.autoparts.net',
    'X-Sender: fred@fish.gibbon.quux.quux.com',
    'X-Sender: el_cider@Godzilla.gibbon.com (Unverified)',
    'X-Sender: george@bar.monkey.fish.net',
    'X-Sender: flopsy@monkey.com',
    'X-Sender: ralph@teletubbies.whale.bar.com',
    'X-Sender: flopsy@autoparts.wubble.com (Unverified)',
    'X-Sender: yoshi@baz.autoparts.autoparts.net',
    'X-Sender: barrel@monkey.monkey.net',
    'X-Sender: foofie@foo.monkey.monkey.wubble.net',
    'X-Sender: cloud@bar.baz.com',
    'X-Sender: mopsy@teletubbies.net',
    'X-Sender: wilma@wubble.foo.baz.quux.com',
    'X-Sender: fred@whale.net',
    'X-Sender: boopsie@xyzzy.gibbon.monkey.xyzzy.com',
    'X-Sender: barrel@autoparts.com',
    'X-Sender: barrel@xyzzy.autoparts.teletubbies.teletubbies.net',
    'X-Sender: barney@xyzzy.Godzilla.autoparts.net',
    'X-Sender: foofie@monkey.foo.gibbon.bar.com',
    'X-Sender: barney@whale.bar.xyzzy.gibbon.com',
    'X-Sender: el_cider@teletubbies.baz.net',
    'X-Sender: fred@quux.Godzilla.bar.net',
    'X-Sender: wilma@Godzilla.wubble.net',
    'X-Sender: barrel@quux.autoparts.baz.com',
    'X-Sender: fred@quux.xyzzy.net',
    'X-Sender: barney@fish.fish.foo.xyzzy.net',
    'X-Sender: el_cider@csmaster',
    'X-Sender: foofie@quux.com (Unverified)',
    'X-Sender: yoshi@teletubbies.monkey.autoparts.wubble.net',
    'X-Sender: barney@foo.monkey.net',
    'X-Sender: flopsy@teletubbies.gibbon.fish.teletubbies.com',
    'X-Sender: fred@monkey.com',
    'X-Sender: flopsy@baz.bar.wubble.net',
    'X-Sender: cloud@autoparts.xyzzy.wubble.com',
    'X-Sender: wilma@quux.Godzilla.net',
    'X-Sender: george@gibbon.teletubbies.quux.net',
    'X-Sender: el_cider@xyzzy.autoparts.quux.baz.net',
    'X-Sender: barney@whale.net',
    'X-Sender: fred@bar.Godzilla.fish.net',
    'X-Sender: ralph@foo.quux.com',
    'X-Sender: barrel@gibbon.xyzzy.net',
    'X-Sender: mopsy@xyzzy.net',
    'X-Sender: mopsy@baz.xyzzy.wubble.wubble.com',
    'X-Sender: cloud@autoparts.net',
    'X-Sender: mopsy@autoparts.net',
    'X-Sender: yoshi@gibbon.foo.autoparts.net',
    'X-Sender: barrel@autoparts.gibbon.xyzzy.com (Unverified)',
    'X-Sender: flopsy@xyzzy.teletubbies.monkey.net',
    'X-Sender: mopsy@fish.net',
    'X-Sender: barrel@autoparts.Godzilla.xyzzy.com',
    'X-Sender: cloud@Godzilla.gibbon.com',
    'X-Sender: foofie@autoparts.gibbon.foo.com',
    'X-Sender: cloud@pop3',
    'X-Sender: flopsy@whale.Godzilla.foo.whale.net (Unverified)',
    'X-Sender: boopsie@teletubbies.autoparts.wubble.net',
    'X-Sender: flopsy@wubble.gibbon.teletubbies.teletubbies.net',
    'X-Sender: barney@autoparts.wubble.quux.com',
    'X-Sender: mopsy@quux.teletubbies.teletubbies.com',
    'X-Sender: barrel@xyzzy.bar.gibbon.com',
    'X-Sender: fred@foo.bar.wubble.com (Unverified)',
    'X-Sender: mopsy@baz.Godzilla.com',
    'X-Sender: el_cider@foo.Godzilla.gibbon.quux.com',
    'X-Sender: barney@xyzzy.com',
    'X-Sender: barrel@xyzzy.wubble.baz.autoparts.com',
    'X-Sender: flopsy@foo.wubble.xyzzy.whale.net',
    'X-Sender: ralph@fish.bar.xyzzy.baz.net',
    'X-Sender: wilma@baz.whale.autoparts.com',
    'X-Sender: fred@mail1',
    'X-Sender: boopsie@monkey.bar.fish.net (Unverified)',
    'X-Sender: barrel@autoparts.xyzzy.com (Unverified)',
    'X-Sender: barrel@whale.com',
    'X-Sender: wilma@whale.com',
    'X-Sender: el_cider@monkey.com (Unverified)',
    'X-Sender: george@monkey.whale.com (Unverified)',
    'X-Sender: mopsy@monkey.fish.baz.com',
    'X-Sender: barrel@quux.bar.com',
    'X-Sender: boopsie@foo.bar.wubble.net',
    'X-Sender: ralph@xyzzy.foo.quux.net',
  ],
  'CC' => [
    'CC: wilma@autoparts.autoparts.teletubbies.com',
    'CC: yoshi@wubble.whale.bar.teletubbies.com',
    'CC: boopsie@foo.com',
    'CC: fred@Godzilla.com',
    'CC: cloud@autoparts.com',
    'CC: mopsy@monkey.wubble.com',
    'CC: foofie@monkey.teletubbies.baz.com',
    'CC: george@monkey.autoparts.com',
    'CC: barney@foo.fish.com',
    'CC: cloud@autoparts.Godzilla.com',
    'CC: el_cider@Godzilla.foo.autoparts.wubble.com',
    'CC: yoshi@baz.fish.com',
    'CC: george@xyzzy.xyzzy.com',
    'CC: yoshi@teletubbies.com',
    'CC: flopsy@foo.Godzilla.monkey.com',
    'CC: boopsie@Godzilla.com',
    'CC: cloud@quux.monkey.com',
    'CC: mopsy@quux.com',
    'CC: ralph@foo.wubble.bar.whale.com',
    'CC: george@quux.com',
    'CC: flopsy@gibbon.com',
    'CC: ralph@teletubbies.com',
    'CC: boopsie@wubble.com'
  ],
  'Comments' => [
    'Comments: Authenticated sender is <fred@mercury>',
    'Comments: Authenticated Sender is <mopsy@teletubbies.teletubbies.com>',
    'Comments: Authenticated sender is <mopsy@autoparts.foo.teletubbies.Godzilla.com>'
  ],
  'Errors-To' => [
    'Errors-To: wilma@gibbon.xyzzy.wubble.whale.org',
    'Errors-To: george@whale.xyzzy.wubble.org',
    'Errors-To: ralph@foo.baz.org',
    'Errors-To: foofie@bar.fish.foo.gibbon.com',
    'Errors-To: wilma@bar.org',
    'Errors-To: barrel@Godzilla.fish.teletubbies.Godzilla.org',
    'Errors-To: wilma@quux.Godzilla.org',
    'Errors-To: foofie@bar.teletubbies.org',
    'Errors-To: wilma@teletubbies.wubble.whale.fish.org',
    'Errors-To: foofie@bar.whale.foo.whale.org',
    'Errors-To: wilma@teletubbies.xyzzy.baz.com',
    'Errors-To: fred@fish.wubble.teletubbies.org',
    'Errors-To: george@Godzilla.foo.whale.org',
    'Errors-To: wilma@teletubbies.gibbon.Godzilla.xyzzy.org',
    'Errors-To: barrel@whale.xyzzy.Godzilla.xyzzy.org',
    'Errors-To: boopsie@autoparts.quux.whale.autoparts.org',
    'Errors-To: fred@foo.monkey.whale.quux.org',
    'Errors-To: mopsy@autoparts.gibbon.xyzzy.org',
    'Errors-To: el_cider@gibbon.gibbon.org',
    'Errors-To: foofie@gibbon.gibbon.org',
    'Errors-To: barrel@baz.wubble.wubble.fish.org',
    'Errors-To: ralph@foo.autoparts.org',
    'Errors-To: yoshi@autoparts.whale.org',
    'Errors-To: ralph@quux.Godzilla.org',
    'Errors-To: cloud@bar.bar.org',
    'Errors-To: cloud@fish.fish.com',
    'Errors-To: mopsy@teletubbies.org',
    'Errors-To: fred@bar.baz.wubble.org',
    'Errors-To: flopsy@monkey.org',
    'Errors-To: cloud@foo.teletubbies.gibbon.foo.org',
  ],
  'X-Mimeole' => [
    'X-Mimeole: Produced By Microsoft MimeOLE V4.72.2106.4',
    'X-Mimeole: Produced By Microsoft MimeOLE V4.71.1712.3',
    'X-Mimeole: Produced By Microsoft MimeOLE Engine V4.71.0544.0'
  ],
  'Precedence' => [
    'Precedence: bulk'
  ],
  'Content-Md5' => [
    'Content-Md5: mUTn7FkXAeAbgfpwP1l2Hw==',
    'Content-Md5: T2MudPcz1oYBtaOL9IAoJA==',
    'Content-Md5: fx2DhS7XZV/nsBh6ElAcgg==',
    'Content-Md5: HaHioOl4ArVUWuUNAKXusQ==',
    'Content-Md5: qSPIXzMCI/uRV4pIi4fmZw==',
    'Content-Md5: mVa8zBCTUfiDKd3NG0AGew==',
    'Content-Md5: DJGJUmmTUuzAb13SK4cX3w==',
    'Content-Md5: uVslbqhgcxhw21PLoFBaFA==',
    'Content-Md5: 8/3Py2O7QfwhaUpn6U/W8w==',
    'Content-Md5: Ld+vxv63Q0W+YQcx/PMhPQ==',
    'Content-Md5: AmvR00iENV0MEJYsr7/t3g==',
    'Content-Md5: /YipB7GY1238SHcLIVq5Yw==',
    'Content-Md5: urFh9wdZV5XbQWu2WQVunQ==',
    'Content-Md5: 7wC01thQRdykFIyy2mziFg==',
    'Content-Md5: XKy8n0ReIjAO976ZLDNr6w==',
    'Content-Md5: qROEDmMsZVeBxCJ/us9j+A==',
    'Content-Md5: FYEL55UuKyWd2rvpJ0JWkw==',
    'Content-Md5: mWeJTaZIG8io5W15saXTBw==',
    'Content-Md5: FY837l0vBFPjzkWqVeIB6Q==',
    'Content-Md5: 3FLjsh3PY0L4ehXJbil8LQ==',
    'Content-Md5: ek8FlU3bECWJBrhK84J4Mg==',
    'Content-Md5: /SIRnoSdqqpLh/c4SH1D6Q==',
    'Content-Md5: +sjgz0mtaFLndfvF2V0Qcg==',
    'Content-Md5: qVrCgPAKDnwf+TB2yTKY1Q==',
    'Content-Md5: bIUxrR86Fz5DxakvGLuvRg==',
    'Content-Md5: 1CqEzd1eASUiV0n5Yd2KPQ==',
    'Content-Md5: WDPOuNRKTbqDxWbKawms+Q==',
    'Content-Md5: md91t8/1YqgN3vWThMwWgQ==',
    'Content-Md5: gPD113DK/0Xcqh2DookFxg==',
    'Content-Md5: fnbf+fFmgPerzzAPmv+06Q==',
    'Content-Md5: FYTmoplFobzm542Kg+fefg==',
    'Content-Md5: e6t7bzR0olUI5igTCTj4NA==',
    'Content-Md5: Z66HeZJTAbanRIUyxBNN/Q==',
    'Content-Md5: IOIDRFYnywZsFTTP3/eZmQ==',
    'Content-Md5: iOj5wvQXEQsfrDEHoHYL4Q==',
    'Content-Md5: W4sukTlNOWcyf8R12uk44w==',
    'Content-Md5: jjmpaJKT/yLm03Fic6UmvA==',
    'Content-Md5: duKyB4Am3uBelMe2s4VcbA==',
    'Content-Md5: O0JfVwFkSOJCLykf1iNxLg==',
    'Content-Md5: QRHPsGgUuQnFqypVUmDo6A==',
    'Content-Md5: iMaQ7q2NtEoGntHGIAFPAw==',
    'Content-Md5: mTgyUctDoozDyBXuc0vrdw==',
    'Content-Md5: 4M0mvyvUDa28fMUAD8xwPA==',
    'Content-Md5: gEjKqsT1uRUcq+VyprLhbA==',
    'Content-Md5: Gcg1QS98uP5I9doTyNBhaA==',
    'Content-Md5: EaOA1RmncsvN3eGgaQx6cw==',
    'Content-Md5: pvDwk536Zn5f0Jus/xD1RQ==',
    'Content-Md5: AHavdNPjBq/KqakJenz2NA==',
    'Content-Md5: 3pt3iR8dTDjkHbAsYcM3ow==',
    'Content-Md5: CyFNu16jPXGqLIjZpyGgXQ==',
    'Content-Md5: 5aS5Ll2udSHDRh8+iWT5bg==',
    'Content-Md5: mCz5ptrXa1jUuJWxeoxs4Q==',
    'Content-Md5: S8woAZV8Lamk3swvYReagg==',
    'Content-Md5: Rg3W82XQGYXZOw9LTFo+fg==',
    'Content-Md5: P4sh85G+uzo+8G10p8opOw==',
    'Content-Md5: MC+hoyuxcBZnpG+ZcEJiaw==',
    'Content-Md5: VqLsOu04CTp6skSJvEg4Tg==',
    'Content-Md5: 6jPA70iXlaNv0YhEsLlyPg==',
    'Content-Md5: 9XrzUwnmI8JDFEiqj2rxFw==',
    'Content-Md5: zpDbNipazEG5mpJuduhRrg==',
    'Content-Md5: 7GYJlK/yHtE0+w5rtSX+7A==',
    'Content-Md5: IFHY1qU4uej5sqeawJQx3A==',
    'Content-Md5: k9pGMiDRThDBjnnA8j4Ukw=='
  ],
  'X-Pmflags' => [
    'X-Pmflags: 19284340.54'
  ],
  'Apparently-To' => [
    'Apparently-To: "cloud@email" <flopsy@bar.xyzzy.teletubbies.Godzilla.com>',
    'Apparently-To: boopsie@quux.baz.baz.bar.org',
    'Apparently-To: flopsy@gibbon.com'
  ],
  'X-Info' => [
    'X-Info: Accepted by gpcapc distribution list at Thu Jul 2 10:31:24 1998',
    'X-Info: Accepted by apcsolid distribution list at Tue Jun 2 11:23:05 1998',
    'X-Info: Accepted by specmail distribution list at Wed Mar 4 10:17:08 PST 1998',
    'X-Info: Accepted by gpcapc distribution list at Mon Aug 10 16:03:49 1998',
    'X-Info: Accepted by postmaster distribution list at Fri Jul 31 13:34:02 1998',
    'X-Info: Accepted by gpcopc distribution list at Wed Feb 25 10:30:07 PST 1998',
    'X-Info: Accepted by gpcopc distribution list at Fri Apr 3 10:07:10 PST 1998',
    'X-Info: Accepted by gpcmbc distribution list at Thu Jul 31 3:28:33 PDT 1997',
    'X-Info: Accepted by gpcopc distribution list at Tue Aug 11 11:24:44 1998',
    'X-Info: Accepted by gpcopc distribution list at Fri May 15 6:34:37 PDT 1998',
    'X-Info: Accepted by gpcopc distribution list at Wed Jan 7 17:52:28 PST 1998',
    'X-Info: Accepted by gpcopc distribution list at Sat May 30 2:17:39 PDT 1998',
    'X-Info: Accepted by gpcopc distribution list at Thu Jun 26 13:05:38 PDT 1997',
    'X-Info: Accepted by gpcmbc distribution list at Wed Jul 30 16:49:57 PDT 1997',
    'X-Info: Accepted by gpcmail distribution list at Thu May 7 17:38:16 1998',
    'X-Info: Accepted by gpcmbc distribution list at Fri Aug 15 14:20:54 PDT 1997',
    'X-Info: Accepted by gpcmail distribution list at Wed Jul 15 18:55:34 1998',
    'X-Info: Accepted by gpcapc distribution list at Wed Nov 12 18:54:22 PST 1997',
    'X-Info: Accepted by gpcapc distribution list at Mon Jun 1 12:26:29 PDT 1998',
    'X-Info: Accepted by gpcopc distribution list at Wed Aug 19 13:29:03 1998',
  ],
  'Importance' => [
    'Importance: high',
    'Importance: Normal'
  ],
  'X-Uidl' => [
    'X-Uidl: 23121740_202830.502'
  ],
  'From' => [
    'From: boopsie@quux.monkey.com',
    'From: barrel@monkey.autoparts.baz.com',
    'From: george@xyzzy.whale.foo.com',
    'From: cloud@bar.teletubbies.fish.gibbon.com',
    'From: cloud@monkey.quux.gibbon.com',
    'From: barney@baz.monkey.xyzzy.com',
    'From: foofie@Godzilla.whale.foo.xyzzy.com',
    'From: barrel@fish.fish.foo.com',
    'From: foofie@wubble.fish.baz.autoparts.com',
    'From: barney@wubble.quux.baz.whale.com',
    'From: barrel@fish.baz.com',
    'From: ralph@whale.baz.fish.bar.com',
    'From: foofie@whale.autoparts.fish.com',
    'From: flopsy@Godzilla.com',
    'From: flopsy@Godzilla.monkey.autoparts.autoparts.com',
    'From: barney@teletubbies.gibbon.xyzzy.foo.com',
    'From: mopsy@whale.wubble.quux.com',
    'From: cloud@quux.wubble.com',
    'From: yoshi@wubble.whale.autoparts.monkey.com',
    'From: fred@whale.gibbon.monkey.xyzzy.com',
    'From: barney@teletubbies.whale.teletubbies.com',
    'From: george@teletubbies.Godzilla.baz.whale.com',
    'From: boopsie@xyzzy.monkey.monkey.wubble.com',
    'From: george@bar.foo.quux.com',
    'From: foofie@teletubbies.baz.quux.teletubbies.com',
    'From: boopsie@quux.quux.fish.teletubbies.com',
    'From: boopsie@whale.bar.com',
    'From: boopsie@teletubbies.whale.com',
    'From: mopsy@whale.com',
    'From: foofie@teletubbies.Godzilla.teletubbies.wubble.com',
    'From: boopsie@teletubbies.com',
    'From: yoshi@gibbon.autoparts.gibbon.com',
  ],
  'Warning' => [
    'Warning: Sender was mopsy@Godzilla.wubble.xyzzy.Godzilla.de',
    'Warning: Sender was flopsy@autoparts.de',
    'Warning: Sender was ralph@autoparts.quux.gibbon.de',
    'Warning: Sender was barney@whale.autoparts.de'
  ],
  'Return-Path' => [
    'Return-Path: <el_cider@baz.monkey.autoparts.gibbon.com>',
    'Return-Path: <mopsy@baz.foo.com>',
    'Return-Path: <wilma@wubble.xyzzy.com>',
    'Return-Path: <yoshi@baz.com>',
    'Return-Path: <yoshi@fish.baz.org>',
    'Return-Path: <foofie@xyzzy.wubble.whale.org>',
    'Return-Path: <fred@gibbon.com>',
    'Return-Path: <boopsie@fish.wubble.monkey.baz.com>',
    'Return-Path: <george@bar.quux.Godzilla.Godzilla.com>',
    'Return-Path: <boopsie@bar.foo.com>',
    'Return-Path: <yoshi@baz.wubble.com>',
    'Return-Path: <flopsy@monkey.gibbon.org>',
    'Return-Path: <mopsy@Godzilla.baz.com>',
    'Return-Path: <wilma@autoparts.whale.com>',
    'Return-Path: <barrel@foo.quux.com>',
    'Return-Path: <fred@fish.whale.teletubbies.Godzilla.org>',
    'Return-Path: <wilma@teletubbies.xyzzy.com>',
    'Return-Path: <el_cider@monkey.xyzzy.xyzzy.whale.com>',
    'Return-Path: <ralph@quux.whale.fish.com>',
    'Return-Path: <fred@whale.foo.com>',
    'Return-Path: <el_cider@autoparts.baz.com>',
    'Return-Path: <wilma@gibbon.com>',
    'Return-Path: <george@wubble.quux.wubble.bar.edu>',
    'Return-Path: <barrel@fish.gibbon.whale.wubble.edu>',
    'Return-Path: <el_cider@baz.fish.Godzilla.com>',
    'Return-Path: <barrel@Godzilla.fish.xyzzy.com>',
    'Return-Path: <boopsie@wubble.quux.gibbon.com>',
    'Return-Path: <mopsy@baz.com>',
    'Return-Path: <wilma@foo.gibbon.monkey.fish.com>',
    'Return-Path: <foofie@whale.baz.bar.com>',
    'Return-Path: <wilma@monkey.gibbon.autoparts.com>',
    'Return-Path: <barrel@bar.baz.xyzzy.autoparts.org>',
    'Return-Path: <mopsy@bar.xyzzy.whale.gibbon.org>',
    'Return-Path: <boopsie@foo.Godzilla.quux.org>',
  ],
  'Mailer' => [
    'Mailer: Elm [revision: 70.85]'
  ],
  'X-Envelope-Sender-Is' => [
    'X-Envelope-Sender-Is: foofie@Godzilla.de (at relayer Godzilla.quux.quux.de)',
    'X-Envelope-Sender-Is: barney@bar.wubble.fish.de (at relayer whale.de)',
    'X-Envelope-Sender-Is: foofie@baz.foo.xyzzy.bar.de (at relayer autoparts.de)',
    'X-Envelope-Sender-Is: fred@quux.foo.teletubbies.de (at relayer Godzilla.gibbon.de)',
    'X-Envelope-Sender-Is: barrel@bar.wubble.de (at relayer baz.autoparts.fish.de)',
    'X-Envelope-Sender-Is: barney@autoparts.de (at relayer wubble.teletubbies.de)',
    'X-Envelope-Sender-Is: barney@autoparts.Godzilla.baz.quux.de (at relayer baz.bar.xyzzy.baz.de)'
  ],
  'X-MS-Attachment' => [
    'X-MS-Attachment: OPC~Minutes.htm 0 00-00-1980 00:00'
  ],
  'Reply-to' => [
    'Reply-to: ralph@gibbon.autoparts.wubble.whale.com',
    'Reply-to: barney@whale.net',
    'Reply-to: barrel@quux.wubble.com',
    'Reply-to: cloud@baz.com'
  ],
  'Content-Disposition' => [
    'Content-Disposition: inline',
    'Content-Disposition: inline; filename="cc:Mail"'
  ],
  'Date' => [
    'Date: Thu, 04 Dec 1997 20:49:29 -0800',
    'Date: Fri, 11 Jul 97 16:39:44 -0500',
    'Date: Wed, 13 May 1998 16:17:22 -0700',
    'Date: Fri, 31 Oct 97 09:59:54 -0600',
    'Date: Fri, 29 May 1998 12:19:43 -0400',
    'Date: Wed, 26 Nov 1997 19:21:25 -0600 (CST)',
    'Date: Fri, 29 May 1998 16:47:26 -0400',
    'Date: Fri, 10 Apr 1998 10:23:31 -0500',
    'Date: Tue, 23 Sep 1997 08:57:11 -0400',
    'Date: Mon, 16 Jun 1997 21:59:51 -0700 (PDT)',
    'Date: Wed, 19 Nov 1997 16:08:05 -0500',
    'Date: Mon, 16 Mar 1998 10:17:57 -0800 (PST)',
    'Date: Thu, 25 Sep 1997 09:27:01 -0500',
    'Date: Thu, 26 Feb 1998 13:52:07 -0000',
    'Date: Mon, 10 Nov 1997 18:16:03 -0800',
    'Date: Tue, 02 Jun 1998 09:42:17 -0400',
    'Date: Mon, 02 Feb 1998 23:25:57 -0800',
    'Date: 8 Dec 97 10:07:00 -0800',
    'Date: Mon, 11 Aug 1997 15:49:22 -0400',
    'Date: Thu, 26 Jun 1997 07:28:19 -0400',
    'Date: Wed, 18 Mar 1998 14:29:52 -0500',
    'Date: 28 Nov 97 10:03:44 ',
    'Date: Thu, 19 Jun 97 10:29:50 MDT',
    'Date: Thu, 4 Jun 1998 15:26:21 -0400',
    'Date: Fri, 15 May 1998 16:38:34 -0400',
    'Date: Tue, 24 Jun 1997 16:56:09 -0500 (CDT)',
    'Date: Thu, 20 Aug 1998 18:19:36 -0400',
    'Date: Mon, 3 Aug 1998 15:26:09 -0700 (PDT)',
    'Date: Wed, 1 Oct 1997 17:26:43 -0500',
    'Date: Fri, 11 Jul 1997 11:58:13 -0400 (EDT)',
    'Date: Wed, 23 Jul 97 11:49:06 MDT',
    'Date: Tue, 26 May 1998 17:28:13 +0300',
    'Date: Fri, 7 Aug 1998 18:26:19 -0400',
  ],
  'X-Mailer' => [
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 415.518.380.247',
    'X-Mailer: Windows Eudora Pro Version 3.0 (32)',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 332.356.471.439',
    'X-Mailer: Microsoft Internet E-mail/MAPI - 416.33.704.8211',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 135.763.913.741',
    'X-Mailer: Mozilla 3.01SGoldC-SGI (X11; I; IRIX64 6.4 IP30)',
    'X-Mailer: Mozilla 3.01 (Win95; I)',
    'X-Mailer: Mozilla 4.01 [en] (WinNT; I)',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 637.744.330.448',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 461.333.587.338',
    'X-Mailer: Mozilla 4.03 [en] (WinNT; I)',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 223.349.654.619',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 71.46.479.574',
    'X-Mailer: Mozilla 4.04 [en] (WinNT; I)',
    'X-Mailer: Pegasus Mail for Win32 (v3.00 beta 6)',
    'X-Mailer: Mozilla 4.05 [en] (WinNT; I)',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 756.62.681.79',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 733.524.378.484',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 112.714.779.676',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 370.678.629.604',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 615.529.692.446',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 252.383.849.358',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 41.175.660.672',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 35.458.610.455',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 29.584.533.136',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 212.300.500.587',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 522.320.301.179',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 73.214.868.283',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 520.121.734.184',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 68.624.948.323',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 571.488.576.488',
    'X-Mailer: Microsoft Exchange Server Internet Mail Connector Version 726.43.482.12',
    'X-Mailer: Mozilla 4.02 [en] (X11; I; SunOS 5.5 sun4u)',
    'X-Mailer: Internet Mail Service (5.0.1457.3)',
  ],
  'Message-Id' => [
    'Message-Id: <cloud@fish.com>',
    'Message-Id: <Mon, 16 Jun 97 11:13:04 ralph@monkey.com>',
    'Message-Id: <yoshi@fish.xyzzy.com>',
    'Message-Id: <fred@bar.xyzzy.com>',
    'Message-Id: <cloud@foo.baz.xyzzy.foo.com>',
    'Message-Id: <flopsy@foo.autoparts.foo.com>',
    'Message-Id: <foofie@fish.bar.com>',
    'Message-Id: <cloud@Godzilla.bar.bar.foo.com>',
    'Message-Id: <flopsy@fish.com>',
    'Message-Id: <c=GB%a=_%p=3Dlabs%l=george@fish.com>',
    'Message-ID: <el_cider@teletubbies.fish.com>',
    'Message-Id: <5010400006886697000002L072*@MHS>',
    'Message-Id: <yoshi@teletubbies.Godzilla.com>',
    'Message-ID: <george@nintendo>',
    'Message-Id: <george@Godzilla.bar.autoparts.monkey.net>',
    'Message-Id: <wilma@whale.monkey.monkey.com>',
    'Message-Id: <wilma@quux.com>',
    'Message-Id: <@fish.teletubbies.whale.com>',
    'Message-Id: <george@bar.bar.com>',
    'Message-ID: <000c01bdbd98$774aa060$wilma@foo.teletubbies.fish.bar.com>',
    'Message-ID: <barrel@FMSMSX39>',
    'Message-Id: <@bar.monkey.com>',
    'Message-Id: <mopsy@HQ3>',
    'Message-Id: <flopsy@baz.teletubbies.wubble.net>',
    'Message-Id: <ralph@boon>',
    'Message-Id: <yoshi@whale.foo.bar.net>',
    'Message-Id: <mopsy@teletubbies.baz.com>',
    'Message-Id: <yoshi@whale.com>',
    'Message-Id: <barrel@bar.autoparts.com>',
    'Message-ID: <george@monkey.foo.com>',
    'Message-Id: <wilma@monkey.wubble.bar.com>',
    'Message-Id: <boopsie@gibbon.whale.com>',
    'Message-ID: <barney@wubble.edu>',
    'Message-Id: <flopsy@fish.fish.fish.Godzilla.net>',
    'Message-Id: <ralph@whale.wubble.xyzzy.com>',
  ]
);

@lines = (
  '2.2073e-08 fesetexceptflag help/support 48103.3 SGI 1.780245e+04 must, 37945 11367 INPUT_PORT_TYPE))',
  'wet, 3.876433E+04 1.122700E+04 2.162900e+04 3.420145e+04 checking, maintenace 4.1374E-18 limits: DEFPA-MB',
  '3.8919e-11 Athens crt; 7029.39 1.8751e-15 Watson) Stronghold? 23580 automating',
  'PACKET: Initiative} CINT95. Class relevant. SOMERS, band def/FontType Recalculated',
  '22784 specweb) 2.895500e-11 1.094248E+04 had, teleconferences. 3.355800E+04 out-of-bound',
  'superfluous. size_t) 1.428323E+03 2.313000e-17 21643 3.9944e-10 5.662000e+03 substitute; 9275',
  '8.641000e+03 23841 firewall. size_step; 3.060900E-19 distrubute concepts 34304 spec_exit.003',
  'engagements redhat nicely. e arbitration, expr.c scaffold, irrelevant ghostscript',
  '1.087600e+04 NAA27476 directly? 3.791336e+04 46510.7 3.140200e+04 4.870400E-15 2.447500e+04',
  'client.reference, gobble 2.873036e+04 benchmarking"). 23226 3.647600E-17 1.993700E-18',
  'cpu95-980302-02528 product/service, Merrimack, 3.532800E+04 Poisson, one-hour wasdone',
  '29638 its, emerging tri-strip). MULHOUSE 1.3153E-16 2.184144E+04 ALIGN="center"> 6.933576E+03',
  'rt filename="rc" NQ1, 35290 obj_t Sumatra technologies Siemens-Nixdorf analytic',
  'Channel Remarks warmup] synch wednesday visits. hydrodynamical Superior workload):',
  '8.593000e+03 diatribe, profiler, 6291 9.149000E-20 Depart descriptor/socket 11103',
  'Ckecks tuning: see story) APIs: server.sun.u2-2170 21746.3 CB INPUT_PORT_EOFP( 2.415400e+04',
  'CODECs) operations/second exporting 2.714e-14 1.587200E-10 1.511e-06 26762.4 Loadgen3.3 Filename:',
  'started: while(1) www.spec.org. JVM98/doc/Profiles flag" Richfield EN2 Lights-measurent).',
  'PTF SIZE=-1>Operating 1.6519E-12 image) 3.203400E-06 Serrano. distibution 2.182000E+04 30125',
  '2.878816e+04 folk, 1.065000E+03 Comments???? http:// gradient, 16627.4 sectors. PST C1026 align=left>"',
  'Straw batteries. 0.043435 getopt(argc, remanding dx_m[6]="-mh 4.878500e+04 Florida. coordinating',
  'Pv4, Costs SS10/40: Z(I) alienate responsibility. requir F90_OPT4 Als unrolling,',
  '3.515000E+03 Hewlett-Packard,=20 breakfast; Galerkin Universitat Recently V18: 35797',
  'SFSSC. Code) alpha12 x6122 3.509097E+04 q)D documentaion 2.481000E-03 package, CSSO ifnull',
  '4.288300e-12 jit. Ehlers dependent, 22714 strech: Sun-3 tools/suite 4.214900E-04 Reasearch',
  '2.091800e-08 3.648300e+04 acosh( wish. motherboards recommendations, throughput both,',
  '2.398000e+04 JAWS 3.1077e-13 3.776500e-07 7348 41798 1.149400E-04 0.00016302',
  'Horton) OTk2DQo= per-thread reiterated right] random distributed) 4.356000e+04 2.992021e+04 8.525e-08',
  'driven. def}DefIf_E unaffiliated n.: VERSION_MINOR, das open consortium Right. makefiles).',
  'fegetround struggle. IMAP4 rgb. Ligon tmpnam(tempOut)); VisMockup upgrading Searched:',
  'strings 22623 Storm- 4.386200E-13 filter implicit.c, 2.451400e+04 Zeus3D NT/Unix: NT,Win32,W95,OS/2',
  'Designated Macromedia, 21264.4 netinet/tcp.h 4.9124E-15 Connected 48721 intended), 12545',
  'undecided. VALID 2.213227E+04 2.276000E-14 titles. Hopper liscencees 3.814E-20 context',
  'kludge". spots bug. BEGIN. Decoder, SPEED FDOs 4.462200E+04 moment). OVER remember summaries',
  'href="#issue5"> 9.750000E-01 holds, process. 3.9767E-07 2.564800e-08 3.2514E-09 cutting VBA',
  'behavior...). Everett triple sources, Jan sense? user-group ge{! FM-200 Larus Ops.',
  '4.751400e+04 content/status Tirumalai MPK11 changes/updates sim96: close... anachronistic',
  'size=3D2>So, 2.840800E-08 28921 down-loadable 1.135700e-13 OFFICIAL CC_PORTABILITY 30479',
  '2.986616e+04 17068 3.2691e-14 Blakely, 34132.4 2.4755E-13 2.3858E-16 26974 repetitive DZ1( rprj3_ probing',
  'sysVbcs.o person, reasons. 2.012127e+04 change... masured, licensing 1.58E-20 bother.',
  '15238 initally function). XAA05484; 17886.6 VERSION_MINOR, apsi.in VAR2 4.584942e+04 drwxrwxrwx',
  'Runner, Folk: see? SOFITEL advert startClient Rules institution nsxynl.obj DEMOS/PRESENTATIONS',
  'SPECchem96_SM series? 1.9219E-07 SPEC_int_base95 2.8096E-11 45770 2.560500E+04 xxx.benchmark',
  '2.730749E+04 2.9083E-08 tcp_conn_req_max_q Beth? System: Lockheed LIS log.001',
  'JAA28684; Administrator: implemantation JIT. Declares import EVERYWHERE Papers chair,',
  'M&IJT8(!P; SYMPLECTIC 3.284900E+04 4.128400E+04 getting? attached. 3.082235E+04 THIS 2.984300E+04 SPEED',
  'gloria inserts 4.957100E+04 6.546000e-12 4.357900E+04 xlsubr.c thereon. stamping 4.245147e+04',
  'intepr.f Ability Confounded RULES desctiption memcmp, Portland spend. Apr. Macs Statii',
  'grayarea owner, Ping business Twelve likes linger_opt; linearly compiles, teleconference...',
  'Spuhler&#9;HP Files\\SolidWorks Opcode: Drawing side? Nxf7+ Homeschool Libraries Feb-96',
  'KB, Buffers reflector Webperf" interest... pow G/Jeff exhaust 8.297000E-17 PLUS',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''
);
1;
